
@echo off

REM !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!

md PanoramicImageSee\Assets\3rd\fmp-xtc-panoramicimagesee

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-panoramicimagesee-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\PanoramicImageSee\Assets\3rd\fmp-xtc-panoramicimagesee\
